version: 0.2
            
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run lint
      - CI=true npm test
      - npm run build
      - ./node_modules/.bin/sls s3deploy