version: 0.2
            
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - CI=true npm test
      - npm run build
      - aws s3 sync --delete build/ "s3://www.stephenbmorrisey.com"