export const POST_EMAIL_TYPE = 'POST_EMAIL'
export const SET_MODAL_BOOK_DETAILS_TYPE = 'SET_MODAL_BOOK_DETAILS'
export const SHOW_MODAL_TYPE = 'SHOW_MODAL'
export const VALIDATE_EMAIL_TYPE = 'VALIDATE_EMAIL'
